# 阿里云更新域名解析文档
# https://help.aliyun.com/document_detail/29776.html
# https://help.aliyun.com/document_detail/29774.html


# 阿里云信息，从阿里云获取填写即可
AliyunData:
  # 阿里云的AccessKey_ID , Access_Key_Secret , region_id
  # 获取方法，参考文档: https://help.aliyun.com/knowledge_detail/38738.html
  AccessKey_ID: 'LTefsJiuyTSDt9m'
  Access_Key_Secret: 'bngMJifPldi0js6DbjsWE3ImxUG'
  region_id: "cn-hangzhou"

# DNS解析信息
UserData:
  # 需要修改的域名
  DomainName: 'baidu.com'
  # 解析的主机
  RR: '*'
  # 解析的记录
  DomainType: 'A'
  # 解析更新的值，如果填写 Auto_Lines ,则从命令行获取,如果命令行为空则去当前设备的外网ip进行更新
  UpdateDomain: 'Auto_Lines'
  #UpdateDomain: '127.0.0.1'